version: '3.4'

services:
  kevinkoesslgithubio:
    image: kevinkoesslgithubio
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
